# Generated by Django 4.1.7 on 2023-03-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('book', models.FileField(default=None, max_length=250, null=True, upload_to='book/')),
                ('description', models.TextField()),
                ('visibility', models.BooleanField()),
                ('cost', models.IntegerField()),
                ('year_of_published', models.IntegerField()),
            ],
        ),
    ]
